FROM openjdk:11.0.1-jre-slim

RUN apt-get update		&& \
    apt-get -y upgrade && \ 
    apt-get install net-tools && \ 
    apt-get install bash-completion

COPY apiserver_start.sh /

ENTRYPOINT [ "/apiserver_start.sh" ]
