version: "3"

networks:
  iudx-net:
    driver: bridge

volumes:
    mongodb:
    mongodb-data:

services:

   mongodb:
    image: mongo
    env_file:
      - .env
    container_name: catalogue-database-mongodb
    hostname: catalogue-database-mongodb
    restart: always
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      - iudx-net
    volumes:
      - mongodb:/var/lib/mongodb/
      - mongodb-data:/data/db/ 
      - ../setup/mongodb:/scripts/  
   apiserver:
    image: vasanthrajaraman/catalogue-apiserver
    container_name: catalogue-apiserver
    hostname: catalogue-apiserver
    restart: always
    ports:
      - "8443:8443"
    networks:
      - iudx-net
    cap_add:
      - ALL
    volumes:
      - ../../iudx-catalogue:/iudx-catalogue/
