#!bin/bash

cd ..

mvn clean compile assembly:single

cp target/catalogue-apiserver-0.0.1-jar-with-dependencies.jar .

cd docker

echo "Stopping Containers"
docker-compose down -v

echo "Starting Containers"
docker-compose up -d

echo "Configuring Catalogue API Server"

echo "Catalogue API Server is UP!"

until nc -z localhost 27017
echo "Checking MondoDB status"

do
    sleep 1
    echo "Waiting to boot..."
done

echo "MongoDB is up at PORT 27017"

echo "Configuring Catalogue"
sleep 5

until nc -z localhost 27017
do
    sleep 1
    echo "Waiting to boot..."
done

docker exec catalogue-database-mongodb ./scripts/mongodb_setup.sh

echo "Catalogue Setup - Created Database (catalogue)"

echo "Catalogue Setup - Created Collections (items and schemas)"

echo "Catalogue Setup Completed"




