#!/bin/bash

JAR_PATH="../target"
JAR_NAME="catalogue-apiserver-0.0.1-fat.jar"
OWNER="iudx"
REPO="iudx-catalogue"

if [ "$1" = "apiserver" ]; then
	echo "Re-installing API Server"
	echo "Downloading jar files from the latest release..." >&2
        
	curl -s https://api.github.com/repos/$OWNER/$REPO/releases/latest \
        | grep browser_download_url | cut -d '"' -f 4 | xargs curl -LJ# > jars.tar.gz

        tar -zxf jars.tar.gz
        mkdir -p $JAR_PATH
        mv $JAR_NAME $JAR_PATH/
        rm -rf jars
        rm jars.tar.gz

	docker restart apiserver
	
	echo "Re-installed API Server"

elif [ "$1" = "mongo" ]; then
	echo "Re-installing MongoDB Server"

	echo "Deleting MongoDB Server Container"
	docker rm -f mongo
	
	echo "Starting MongoDB Containers"
	docker-compose up -d mongodb

	echo "Checking MondoDB status"

	until nc -z localhost 27017
	do
	    sleep 1
	    echo "Waiting to boot..."
	done

	echo "MongoDB is up at PORT 27017"

else
	echo "Invalid argument passed."
fi
